### ISSUE TITLE
Add track button does not work

### ISSUE THREAD

**Issue by inodb** [cBioPortal/clinical-timeline#56]
Currently the button for showing a track after hiding it does not work:
![addtrack_button_notworking](https://cloud.githubusercontent.com/assets/1334004/13467444/485f55e2-e06c-11e5-9f6e-28288bf707b2.gif)

Expected behavior:
After clicking on the name of a track in the 'Add Track' button tooltip the track should appear again.

**Comment by anumnaveed1989** [comment]
I am working on fixing this issue.

**Comment by inodb** [comment]
:+1:

**Comment by inodb** [comment]
@anumnaveed1989 Sorry, looks like somebody else fixed this already. I've started a list with more issues of a similar difficulty level: https://github.com/cBioPortal/clinical-timeline/issues?q=is%3Aopen+is%3Aissue+label%3A%22Difficulty+Novice%22. I saw that multiple students can be selected for the same project: http://www.google-melange.com/gsoc/document/show/gsoc_program/google/gsoc2015/help_page#11._What_happens_if_two_students_are

**Comment by anumnaveed1989** [comment]
Hi Ino,

Thanks for notifying my about this. I really appreciate it. Actually this
was reason why I suggested to assign the tasks on github so that there is
no duplicate of effort in fixing the same bug. However, since yesterday, I
have set up the development environment of CBIOPortal on my local system. I
have successfully bulit the project from source using maven and now
deploying and testing it in Tomcat.

Thanks and looking forward to work with you in GSoC.

Regards, Anum

**Comment by anumnaveed1989** [comment]
Hi Ino,

I followed the steps defined in
https://github.com/cBioPortal/cbioportal/wiki to set up cbioportal on
WINDOWS 7. But webapp doesn't run in tomcat. I get the following error in
logs.

INFO: Deploying web application archive D:\tomcat\webapps\cbioportal.war
Mar 03, 2016 7:38:39 PM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable
debug logging for this logger for a complete list of JARs that were scanned
but no TLDs were found in them. Skipping unneeded JARs during scanning can
improve startup time and JSP compilation time.
Mar 03, 2016 7:38:54 PM org.apache.catalina.core.StandardContext
startInternal
SEVERE: One or more listeners failed to start. Full details will be found
in the appropriate container log file
Mar 03, 2016 7:38:54 PM org.apache.catalina.core.StandardContext
startInternal
SEVERE: Context [/cbioportal] startup failed due to previous errors
Mar 03, 2016 7:38:54 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive
D:\tomcat\webapps\cbioportal.war has finished in 51,250 ms

The browser shows me 404 not found error.

Can this be a problem of setting PORTAL_HOME="/path/to/properties" in
windows?

Regards,

**Comment by anumnaveed1989** [comment]
Hi Ino,

After fixing various settings, I have managed to successfully managed to
install and deploy cbioportal on my local system. Here is the screenshot of
my environment: I will now pick up the bug and fix it. Thanks for your help.

[image: Inline image 1]

Regards,
